import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

test('editor store and sidebar include the AI tab as a first-class sidebar surface', async () => {
  const [store, sidebar, app] = await Promise.all([
    readFile(new URL('../src/store/editor.ts', import.meta.url), 'utf8'),
    readFile(new URL('../src/components/Sidebar/Sidebar.tsx', import.meta.url), 'utf8'),
    readFile(new URL('../src/App.tsx', import.meta.url), 'utf8'),
  ])

  assert.match(store, /export type SidebarTab = 'ai' \| 'files' \| 'outline' \| 'search' \| 'recent'/)
  assert.match(sidebar, /\{ id: 'ai', icon: 'sparkles', title: t\('sidebar\.ai'\) \}/)
  assert.match(sidebar, /data-sidebar-tab=\{id\}/)
  assert.match(sidebar, /<AISidebarPanel activePeekView=\{aiPeekView\} onPeekChange=\{onAiPeekViewChange\} \/>/)
  assert.match(app, /<AISidebarPeekRail view=\{aiPeekView\} onClose=\{\(\) => setAiPeekView\(null\)\} \/>/)
})

test('AI sidebar keeps quick actions in the sidebar and moves dense content into a peek rail', async () => {
  const [panel, rail, shared] = await Promise.all([
    readFile(new URL('../src/components/Sidebar/AISidebarPanel.tsx', import.meta.url), 'utf8'),
    readFile(new URL('../src/components/Sidebar/AISidebarPeekRail.tsx', import.meta.url), 'utf8'),
    readFile(new URL('../src/components/Sidebar/aiSidebarShared.ts', import.meta.url), 'utf8'),
  ])

  assert.match(shared, /const SIDEBAR_TAB_SOURCE = 'sidebar-tab' as AIComposerSource/)
  assert.match(shared, /createAITemplateOpenDetail\('ask', t, SIDEBAR_TAB_SOURCE\)/)
  assert.match(shared, /createAITemplateOpenDetail\('continueWriting', t, SIDEBAR_TAB_SOURCE\)/)
  assert.match(panel, /data-ai-sidebar-open-composer="true"/)
  assert.match(panel, /data-ai-sidebar-action=\{action\.id\}/)
  assert.match(panel, /data-ai-sidebar-peek-trigger=\{view\}/)
  assert.match(panel, /data-ai-sidebar-recent-session="true"/)
  assert.match(panel, /sessionHistory\.length > 0/)
  assert.match(rail, /data-ai-sidebar-peek=\{view\}/)
  assert.match(rail, /data-ai-sidebar-template=\{template\.id\}/)
  assert.match(rail, /getAIDocumentThreadKey\(activeTab\.id, activeTab\.path\)/)
  assert.match(rail, /data-ai-sidebar-history-search="true"/)
  assert.match(rail, /data-ai-sidebar-history-status-filter="true"/)
  assert.match(rail, /data-ai-sidebar-history-workspace-filter="true"/)
  assert.match(rail, /data-ai-sidebar-history-pinned-filter="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-rank="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-reset="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-preview="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-preview-item=\{candidate\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-provider-preview-raw="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-status-filter="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-budget-filter="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-export="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-insights="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-insight-query=\{item\.query\}/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-compare="true"/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-compare-entry=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-compare-toggle=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-replay=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-provider-audit-entry=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-workspace-handoff="true"/)
  assert.match(rail, /data-ai-sidebar-history-workspace-run="true"/)
  assert.match(rail, /data-ai-sidebar-history-workspace-target=\{target\.documentKey\}/)
  assert.match(rail, /data-ai-sidebar-history-preset=\{preset\}/)
  assert.match(rail, /data-ai-sidebar-history-export="true"/)
  assert.match(rail, /data-ai-sidebar-history-import="true"/)
  assert.match(rail, /data-ai-sidebar-history-collection-input="true"/)
  assert.match(rail, /data-ai-sidebar-history-collection-create="true"/)
  assert.match(rail, /data-ai-sidebar-history-collection-create-policy="true"/)
  assert.match(rail, /data-ai-sidebar-history-collection-create-policy-mode="true"/)
  assert.match(rail, /data-ai-sidebar-history-collection-create-policy-budget="true"/)
  assert.match(rail, /data-ai-sidebar-history-collection=\{collection\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-collection-policy-panel=\{collection\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-collection-policy-mode=\{collection\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-collection-policy-budget=\{collection\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-view-input="true"/)
  assert.match(rail, /data-ai-sidebar-history-view-create="true"/)
  assert.match(rail, /data-ai-sidebar-history-view-create-preset="true"/)
  assert.match(rail, /data-ai-sidebar-history-view-create-preset-budget="true"/)
  assert.match(rail, /data-ai-sidebar-history-view-create-preset-workspace-run="true"/)
  assert.match(rail, /data-ai-sidebar-history-view=\{view\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-view-workspace-run=\{view\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-view-automation-run=\{view\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-view-preset-panel=\{view\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-view-preset-status=\{view\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-view-preset-pinned=\{view\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-view-preset-workspace-run=\{view\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-view-preset-budget=\{view\.id\}/)
  assert.match(rail, /data-ai-sidebar-history-clear-current="true"/)
  assert.match(rail, /data-ai-sidebar-history-clear-all="true"/)
  assert.match(rail, /data-ai-sidebar-session-history=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-session-pin=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-session-remove=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-session-reuse=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-session-restore=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-session-match=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-session-provider-reason=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-session-workspace=\{entry\.id\}/)
  assert.match(rail, /data-ai-sidebar-session-workspace-task=\{task\.taskId\}/)
  assert.match(rail, /data-ai-sidebar-cross-history-empty="true"/)
  assert.match(rail, /sessionHistoryByDocument/)
  assert.match(rail, /retrieveAIHistoryCandidates\(/)
  assert.match(rail, /rerankAIHistoryCandidatesWithProvider\(/)
  assert.match(rail, /historyRetentionPreset/)
  assert.match(rail, /formatPrimaryShortcut\('J'\)/)
})
