import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

test('App wires Ctrl/Cmd+J to open the AI composer and mounts the composer shell', async () => {
  const app = await readFile(new URL('../src/App.tsx', import.meta.url), 'utf8')

  assert.match(app, /const AIComposer = lazy\(\(\) => import\('\.\/components\/AI\/AIComposer'\)\)/)
  assert.match(app, /matchesPrimaryShortcut\(event, \{ key: 'j' \}\)/)
  assert.match(app, /dispatchEditorAIOpen\(\{ source: 'shortcut' \}\)/)
  assert.match(app, /\{aiComposerOpen && \(/)
})

test('CodeMirrorEditor renders the selection bubble and listens for AI open/apply events', async () => {
  const editor = await readFile(new URL('../src/components/Editor/CodeMirrorEditor.tsx', import.meta.url), 'utf8')

  assert.match(editor, /import AISelectionBubble from '\.\.\/AI\/AISelectionBubble'/)
  assert.match(editor, /mergeSelectionBubbleRects/)
  assert.match(editor, /const container = containerRef\.current/)
  assert.match(editor, /const visualSelectionTo = selection\.to > selection\.from \? selection\.to - 1 : selection\.to/)
  assert.match(editor, /view\.coordsAtPos\(selection\.from,\s*1\)\s*\?\?\s*view\.coordsAtPos\(selection\.from\)/)
  assert.match(editor, /view\.coordsAtPos\(visualSelectionTo,\s*-1\)\s*\?\?\s*view\.coordsAtPos\(visualSelectionTo\)/)
  assert.match(editor, /const selectionRect = mergeSelectionBubbleRects\(selectionStartCoords,\s*selectionEndCoords\)/)
  assert.match(editor, /const shellRect = shell\.getBoundingClientRect\(\)/)
  assert.match(editor, /const editorRect = container\.getBoundingClientRect\(\)/)
  assert.match(editor, /const scaleX = Math\.max\(view\.scaleX \|\| 1,\s*0\.0001\)/)
  assert.match(editor, /const scaleY = Math\.max\(view\.scaleY \|\| 1,\s*0\.0001\)/)
  assert.match(editor, /const lineHeight = Number\.isFinite\(view\.defaultLineHeight\) \? view\.defaultLineHeight : 0/)
  assert.match(editor, /const positionInEditor = computeAISelectionBubblePosition\(selectionRect,\s*\{/)
  assert.match(editor, /gap: Math\.max\(lineHeight \/ 4,\s*2\)/)
  assert.match(editor, /if \(!Number\.isFinite\(nextTop\) \|\| !Number\.isFinite\(nextLeft\)\) \{\s*setSelectionBubble\(null\)/)
  assert.match(editor, /top: nextTop/)
  assert.match(editor, /left: nextLeft/)
  assert.match(editor, /document\.addEventListener\(EDITOR_AI_OPEN_EVENT, handleAIOpen\)/)
  assert.match(editor, /document\.addEventListener\(EDITOR_AI_APPLY_EVENT, handleAIApply\)/)
  assert.match(editor, /onSizeChange=\{handleSelectionBubbleSizeChange\}/)
  assert.match(editor, /new ResizeObserver\(\(\) => scheduleSelectionBubbleUpdate\(\)\)/)
})

test('CodeMirrorEditor coalesces high-frequency selection bubble updates through requestAnimationFrame', async () => {
  const editor = await readFile(new URL('../src/components/Editor/CodeMirrorEditor.tsx', import.meta.url), 'utf8')

  assert.match(editor, /const scheduleSelectionBubbleUpdate = useCallback\(/)
  assert.match(editor, /selectionBubbleRafRef\.current = requestAnimationFrame\(/)
  assert.match(editor, /cancelAnimationFrame\(selectionBubbleRafRef\.current\)/)
  assert.match(editor, /const handleScroll = \(\) => scheduleSelectionBubbleUpdate\(view\)/)
  assert.match(editor, /const handleResize = \(\) => scheduleSelectionBubbleUpdate\(view\)/)
  assert.match(editor, /scheduleSelectionBubbleUpdate\(view\)\s*\n\s*scheduleTableExitFocusRestore\(view\)/)
})

test('MarkdownPreview useMemo deps omit the i18n t function to avoid redundant HTML rebuilds', async () => {
  const source = await readFile(
    new URL('../src/components/Preview/MarkdownPreview.tsx', import.meta.url),
    'utf8'
  )

  // previewHtml useMemo deps
  assert.match(
    source,
    /\[documentPath, html, i18n\.language, isTauri, previewOrigin, resolvedExternalImages, resolvedLocalImages\]/
  )
  // mermaidLabels useMemo deps — only language, no t
  assert.match(source, /\[i18n\.language\]\s*\)\s*\n\s*const getMermaidTheme/)
})

test('AI setup panel owns AI connection settings while ThemePanel stays editor-only', async () => {
  const [themePanel, aiPanel, section, globalCss] = await Promise.all([
    readFile(new URL('../src/components/ThemePanel/ThemePanel.tsx', import.meta.url), 'utf8'),
    readFile(new URL('../src/components/AI/AISetupPanel.tsx', import.meta.url), 'utf8'),
    readFile(new URL('../src/components/ThemePanel/AISettingsSection.tsx', import.meta.url), 'utf8'),
    readFile(new URL('../src/global.css', import.meta.url), 'utf8'),
  ])

  assert.doesNotMatch(themePanel, /AISettingsSection/)
  assert.match(aiPanel, /data-ai-setup-panel="true"/)
  assert.match(aiPanel, /t\('ai\.setup\.title'\)/)
  assert.match(aiPanel, /<AISettingsSection \/>/)
  assert.match(section, /t\('ai\.connection\.baseUrl'\)/)
  assert.match(section, /t\('ai\.connection\.model'\)/)
  assert.match(section, /t\('ai\.connection\.apiKey'\)/)
  const formSectionOrder = section.slice(section.indexOf('{renderOCIAuthSection({'), section.indexOf('{aiError ? ('))
  const ociAuthIndex = formSectionOrder.indexOf('{renderOCIAuthSection({')
  const mcpExecutionIndex = formSectionOrder.indexOf('{renderMCPExecutionSection({')
  const unstructuredIndex = formSectionOrder.indexOf('{renderUnstructuredSection({')
  assert.notEqual(ociAuthIndex, -1)
  assert.notEqual(mcpExecutionIndex, -1)
  assert.notEqual(unstructuredIndex, -1)
  assert.ok(ociAuthIndex < mcpExecutionIndex)
  assert.ok(mcpExecutionIndex < unstructuredIndex)
  assert.match(section, /ociAuthProfiles: scope === 'oci-auth' \? aiOCIAuthProfiles : persistedConfig\.ociAuthProfiles/)
  assert.match(section, /structuredStores: scope === 'structured' \? aiStructuredStores : persistedConfig\.structuredStores/)
  assert.match(section, /mcpExecutionProfiles: scope === 'mcp-execution' \? aiMCPExecutionProfiles : persistedConfig\.mcpExecutionProfiles/)
  assert.doesNotMatch(section, /structuredStores: aiStructuredStores\.map\(\(store\) => \(\{[\s\S]*defaultMode: 'sql-draft',[\s\S]*executionAgentProfileId: null,[\s\S]*\}\)\)/)
  assert.match(section, /t\('ai\.connection\.ociAuthProfiles'\)/)
  assert.match(section, /DEFAULT_OCI_IAM_CONFIG_FILE/)
  assert.match(section, /chooseOCIKeyFile/)
  assert.match(section, /t\('ai\.connection\.keyFilePassphrase'\)/)
  assert.match(section, /storeAIOCIKeyFilePassphrase/)
  assert.match(section, /clearAIOCIKeyFilePassphrase/)
  assert.doesNotMatch(section, /securityTokenFile/)
  assert.match(section, /t\('ai\.connection\.mcpExecutionProfiles'\)/)
  assert.match(section, /t\('ai\.connection\.mcpConfigJson'\)/)
  assert.doesNotMatch(section, /t\('ai\.connection\.mcpToolName'\)/)
  assert.match(section, /tryParseAIOracleMCPConfigJson/)
  assert.doesNotMatch(section, /buildAIOracleMCPConfigJson/)
  assert.doesNotMatch(section, /t\('ai\.connection\.mcpServerUrl'\)/)
  assert.doesNotMatch(section, /t\('ai\.connection\.mcpCommand'\)/)
  assert.doesNotMatch(section, /t\('ai\.connection\.mcpArgs'\)/)
  assert.doesNotMatch(section, /<FormField label=\{t\('ai\.connection\.description'\)\} meta=\{t\('ai\.connection\.optional'\)\}>[\s\S]*profile\.description/u)
  assert.match(section, /import AppIcon from '\.\.\/Icons\/AppIcon'/)
  assert.match(section, /type AISettingsSaveScope =/)
  assert.match(section, /function buildAIProviderConfigForScope\(scope: AISettingsSaveScope\): AIProviderConfig/)
  assert.match(section, /baseUrl: scope === 'connection' \? aiBaseUrl : persistedConfig\.baseUrl/)
  assert.match(section, /model: scope === 'connection' \? aiModel : persistedConfig\.model/)
  assert.match(section, /project: scope === 'connection' \? aiProject : persistedConfig\.project/)
  assert.match(section, /ociAuthProfiles: scope === 'oci-auth' \? aiOCIAuthProfiles : persistedConfig\.ociAuthProfiles/)
  assert.match(section, /unstructuredStores: scope === 'unstructured' \? aiUnstructuredStores : persistedConfig\.unstructuredStores/)
  assert.match(section, /structuredStores: scope === 'structured' \? aiStructuredStores : persistedConfig\.structuredStores/)
  assert.match(section, /mcpExecutionProfiles: scope === 'mcp-execution' \? aiMCPExecutionProfiles : persistedConfig\.mcpExecutionProfiles/)
  assert.match(section, /hostedAgentProfiles: scope === 'hosted-agent' \? aiHostedAgentProfiles : persistedConfig\.hostedAgentProfiles/)
  assert.match(section, /scope === 'connection' && aiApiKey\.trim\(\)/)
  assert.match(section, /scope === 'oci-auth' && savedConfig\.provider === 'oci-responses'/)
  assert.match(section, /scope === 'hosted-agent' && savedConfig\.provider === 'oci-responses'/)
  assert.match(section, /refreshAiProviderStateAfterScopedSave\(scope\)/)
  assert.match(section, /applyProviderStateToSavedScope\(state, scope\)/)
  assert.match(section, /function ConfigItemHeader\(/)
  assert.equal((section.match(/<ConfigItemHeader/g) ?? []).length, 5)
  assert.match(section, /<AppIcon name="save" size=\{12\} \/>/)
  assert.match(section, /<AppIcon name="save" size=\{13\} \/>/)
  assert.match(section, /onSave: \(\) => void saveAiConnection\('oci-auth'\)/)
  assert.match(section, /onSave: \(\) => void saveAiConnection\('mcp-execution'\)/)
  assert.match(section, /onSave: \(\) => void saveAiConnection\('unstructured'\)/)
  assert.match(section, /onSave: \(\) => void saveAiConnection\('structured'\)/)
  assert.match(section, /onSave: \(\) => void saveAiConnection\('hosted-agent'\)/)
  assert.match(section, /style=\{itemSaveActionStyle\}\s*\n\s*disabled=\{aiLoading\}/)
  assert.match(section, /data-ai-semantic-metadata="advanced"/)
  assert.match(section, /data-ai-metadata-diagnostics="true"/)
  assert.match(section, /function DisclosureSummary\(/)
  assert.match(section, /ai-settings-disclosure-summary/)
  assert.match(section, /<AppIcon name="chevronRight" size=\{13\} className="ai-settings-disclosure-chevron" \/>/)
  assert.match(section, /t\('ai\.connection\.semanticMetadata'\)/)
  assert.match(section, /t\('ai\.connection\.semanticMetadataMeta'\)/)
  assert.match(section, /t\('ai\.connection\.enrichmentDefaultMode'\)/)
  assert.match(section, /store\.enrichmentDefaultMode === 'partial'/)
  assert.match(section, /t\('ai\.connection\.enrichmentDiagnostics'\)/)
  assert.match(section, /data-ai-enrichment-job-summary="true"/)
  assert.match(section, /gridTemplateColumns: 'repeat\(auto-fit, minmax\(min\(12rem, 100%\), 1fr\)\)'/)
  assert.match(section, /className="grid min-w-0 max-w-full gap-2 overflow-hidden rounded-lg border/)
  assert.match(section, /className=\{`\$\{technicalInputClassName\} min-w-0 max-w-full overflow-x-auto overflow-y-auto whitespace-pre/)
  assert.match(section, /data-ai-enrichment-failure-details="true"/)
  assert.match(section, /extractEnrichmentJobDiagnostics/)
  assert.match(section, /extractLatestEnrichmentJob/)
  assert.match(section, /latestJobDetailError/)
  assert.match(section, /t\('ai\.connection\.latestEnrichmentJob'\)/)
  assert.match(section, /t\('ai\.connection\.enrichmentFailureDetails'\)/)
  assert.match(section, /t\('ai\.connection\.enrichmentNoFailureDetails'\)/)
  assert.match(section, /buildEnrichmentJobRawResponse\(result, 'build'\)/)
  assert.match(section, /buildEnrichmentJobRawResponse\(result, 'refresh'\)/)
  assert.match(section, /buildEnrichmentJobRawResponse\(result, 'get'\)/)
  assert.match(section, /delete next\[store\.id\]/)
  assert.match(section, /getEnrichmentJobRawResponseLabelKey\(enrichmentJobResult\?\.source\)/)
  assert.match(section, /t\(enrichmentJobRawResponseLabel\)/)
  assert.match(section, /if \(source === 'build'\) return 'ai\.connection\.enrichmentRawBuildMetadataResponse'/)
  assert.match(section, /if \(source === 'refresh'\) return 'ai\.connection\.enrichmentRawRefreshJobsResponse'/)
  assert.match(section, /if \(source === 'get'\) return 'ai\.connection\.enrichmentRawGetJobResponse'/)
  assert.match(section, /return 'ai\.connection\.enrichmentRawResponse'/)
  assert.match(section, /t\('ai\.connection\.compartmentId'\)/)
  assert.match(section, /t\('ai\.connection\.required'\)/)
  const structuredSection = section.slice(section.indexOf('function renderStructuredSection('))
  assert.match(structuredSection, /checked=\{store\.isDefault\}/)
  assert.match(structuredSection, /setAiStructuredStores\(\(current\) =>\s*current\.map\(\(item\) => \(\{/)
  assert.match(structuredSection, /isDefault: item\.id === store\.id \? event\.target\.checked : false/)
  assert.match(structuredSection, /t\('ai\.connection\.defaultStore'\)/)
  const structuredStoreFields = structuredSection.slice(
    structuredSection.indexOf("<FormField label={t('ai.connection.label')}>"),
    structuredSection.indexOf('<div className="grid grid-cols-1 gap-2 sm:grid-cols-2">')
  )
  assert.ok(structuredStoreFields.indexOf("t('ai.connection.compartmentId')") < structuredStoreFields.indexOf("t('ai.connection.semanticStoreId')"))
  const metadataDiagnostics = section.slice(
    section.indexOf('data-ai-metadata-diagnostics="true"'),
    section.indexOf("t('ai.connection.enrichmentJobIdHint')")
  )
  assert.doesNotMatch(metadataDiagnostics, /t\('ai\.connection\.compartmentId'\)/)
  assert.match(section, /t\('ai\.connection\.enrichmentJobId'\)/)
  assert.match(section, /t\('ai\.connection\.enrichmentJobIdMeta'\)/)
  assert.match(section, /t\('ai\.connection\.enrichmentJobIdHint'\)/)
  assert.match(section, /t\('ai\.connection\.invalidEnrichmentJobIdHint'\)/)
  assert.match(section, /notices\.aiEnrichmentJobInvalidIdTitle/)
  assert.match(section, /compartmentId: event\.target\.value/)
  assert.match(section, /const compartmentId = \(store\.compartmentId \|\| store\.storeOcid \|\| ''\)\.trim\(\)/)
  assert.match(section, /listAIEnrichmentJobs\(\{\s*structuredStoreId: store\.id,\s*compartmentId,/)
  assert.match(section, /!\(store\.compartmentId \|\| store\.storeOcid \|\| ''\)\.trim\(\)/)
  assert.match(section, /!\(store\.compartmentId \|\| store\.storeOcid \|\| ''\)\.trim\(\) \|\|\s*!store\.semanticStoreId/)
  assert.match(section, /ENRICHMENT_JOB_ID_PATTERN[\s\S]*enrichmentjob[\s\S]*JB/)
  assert.match(section, /function normalizeEnrichmentJobIdInput\(input: string\): string/)
  assert.match(section, /function isLikelyOracleEnrichmentJobId\(value: string\): boolean/)
  assert.match(section, /resolveEnrichmentJobIdForAction\(store\)/)
  assert.match(section, /placeholder="JB253785cc-2d6f-413e-b47e-a07e3b462a8c"/)
  assert.match(section, /enrichmentDefaultMode: event\.target\.value === 'partial' \? 'partial' : 'full'/)
  assert.match(section, /t\('ai\.connection\.defaultMode'\)/)
  assert.doesNotMatch(section, /updateStructuredStore\(store\.id, \(current\) => \(\{ \.\.\.current, vectorStoreId/u)
  assert.doesNotMatch(section, /t\('ai\.connection\.executionAgentProfile'\)/)
  assert.match(globalCss, /\.ai-settings-disclosure-summary:hover/)
  assert.match(globalCss, /\.ai-settings-disclosure-summary:focus-visible/)
  assert.match(globalCss, /\.ai-settings-disclosure\[open\] > \.ai-settings-disclosure-summary/)
  assert.match(globalCss, /\.ai-settings-disclosure\[open\] > \.ai-settings-disclosure-summary \.ai-settings-disclosure-chevron/)
  assert.match(globalCss, /prefers-reduced-motion: reduce/)
  assert.match(section, /generateAIEnrichmentJob/)
  assert.match(section, /listAIEnrichmentJobs/)
  assert.match(section, /getAIEnrichmentJob/)
  assert.doesNotMatch(section, /cancelAIEnrichmentJob/)
  assert.doesNotMatch(section, /cancelEnrichmentJob/)
  assert.doesNotMatch(section, /t\('ai\.connection\.cancelEnrichmentJob'\)/)
  assert.match(section, /aiEnrichmentJobResults/)
  assert.match(section, /notices\.aiEnrichmentJobErrorTitle/)
  assert.doesNotMatch(section, /t\('ai\.preferences\.defaultWriteTarget'\)/)
  assert.doesNotMatch(section, /t\('ai\.preferences\.selectedTextRole'\)/)
  assert.doesNotMatch(section, /data-ai-history-provider-settings="true"/)
  assert.doesNotMatch(section, /t\('ai\.preferences\.historyProviderTitle'\)/)
  assert.doesNotMatch(section, /t\('ai\.preferences\.historyProviderEnabled'\)/)
  assert.doesNotMatch(section, /t\('ai\.preferences\.historyProviderBudget'\)/)
})

test('AI settings keep secret inputs in a submit form while matching the Settings panel section style', async () => {
  const section = await readFile(new URL('../src/components/ThemePanel/AISettingsSection.tsx', import.meta.url), 'utf8')

  assert.match(section, /function handleSubmit\(event: FormEvent<HTMLFormElement>\)/)
  assert.match(section, /event\.preventDefault\(\)\s*\n\s*void saveAiConnection\('connection'\)/)
  assert.match(section, /<form data-ai-settings="true" className="space-y-2" onSubmit=\{handleSubmit\}>/)
  assert.match(section, /const hasChildren = Children\.count\(children\) > 0/)
  assert.match(section, /\{hasChildren \? <div className="grid gap-2 border-l pl-3" style=\{sectionBodyStyle\}>\{children\}<\/div> : null\}/)
  assert.match(section, /function SettingsSectionHeader\(/)
  assert.match(section, /<fieldset className="min-w-0 border-t pt-2" style=\{sectionDividerStyle\}>/)
  assert.match(section, /<span className="h-3\.5 w-1 rounded-full" style=\{sectionAccentStyle\} aria-hidden="true" \/>/)
  assert.match(section, /className="cursor-pointer rounded-lg border px-2\.5 py-1 text-\[11px\] font-medium transition-colors"/)
  assert.doesNotMatch(section, /autoComplete="off"/)
  assert.match(section, /<legend className="sr-only">\{t\('ai\.connection\.title'\)\}<\/legend>/)
  assert.match(section, /<legend className="sr-only">\{title\}<\/legend>/)
  assert.match(section, /<SettingsSectionHeader[\s\S]*title=\{t\('ai\.connection\.title'\)\}[\s\S]*className="text-\[11px\] font-medium"/)
  assert.match(section, /<span>\{t\('ai\.connection\.saveProvider'\)\}<\/span>/)
  assert.match(section, /<p>\{t\('ai\.connection\.providerDescription'\)\}<\/p>/)
  assert.match(section, /<div className="grid gap-2 border-l pl-3" style=\{sectionBodyStyle\}>[\s\S]*t\('ai\.connection\.providerDescription'\)[\s\S]*<FormField label=\{t\('ai\.connection\.baseUrl'\)\}>/)
  assert.match(section, /type="url"\s*\n\s*inputMode="url"\s*\n\s*autoComplete="url"\s*\n\s*value=\{aiBaseUrl\}/)
  assert.match(section, /type="url"\s*\n\s*inputMode="url"\s*\n\s*autoComplete="url"\s*\n\s*value=\{profile\.domainUrl\}/)
  assert.match(section, /<FormField label=\{t\('ai\.connection\.apiKey'\)\}>[\s\S]*<div className="flex gap-2">[\s\S]*type="password"[\s\S]*min-w-0 flex-1[\s\S]*onClick=\{\(\) => void clearDirectApiKey\(\)\}[\s\S]*\{t\('ai\.connection\.clearKey'\)\}/)
  assert.match(section, /<FormField label=\{t\('ai\.connection\.clientSecret'\)\}>[\s\S]*<div className="flex gap-2">[\s\S]*type="password"[\s\S]*min-w-0 flex-1[\s\S]*onClick=\{\(\) => void clearHostedAgentSecret\(profile\.id\)\}[\s\S]*\{t\('ai\.connection\.clearClientSecret'\)\}/)
  assert.match(section, /t\('ai\.connection\.clientId'\)[\s\S]*t\('ai\.connection\.clientSecret'\)[\s\S]*t\('ai\.connection\.scope'\)/)
  assert.match(section, /type="password"\s*\n\s*autoComplete="new-password"/)
  assert.match(section, /className="flex shrink-0 items-center gap-2"[\s\S]*type="submit"\s*\n\s*className="inline-flex cursor-pointer items-center gap-1\.5 rounded-lg px-3 py-1\.5 text-xs font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-45"/)
  assert.doesNotMatch(section, /<div className="flex">\s*<button\s*type="submit"\s*className="rounded-lg px-3 py-2 text-xs font-medium transition-colors"/)
  assert.match(section, /aria-label=\{`\$\{t\('ai\.connection\.save'\)\} \$\{title\}`\}/)
  assert.match(section, /type="button"\s*\n\s*aria-label=\{`\$\{t\('ai\.connection\.save'\)\} \$\{title\}`\}\s*\n\s*onClick=\{onSave\}/)
  assert.doesNotMatch(section, /<div className="flex flex-wrap gap-2">[\s\S]*clearDirectApiKey/)
})

test('AI settings surface resolved hosted-agent URLs and notify the composer when provider state changes', async () => {
  const [section, runtime] = await Promise.all([
    readFile(new URL('../src/components/ThemePanel/AISettingsSection.tsx', import.meta.url), 'utf8'),
    readFile(new URL('../src/components/AI/useAIComposerRuntime.ts', import.meta.url), 'utf8'),
  ])

  assert.match(section, /dispatchAIProviderStateChanged\(\)/)
  assert.match(section, /buildHostedAgentTokenUrlPreview\(profile\.domainUrl\)/)
  assert.match(section, /buildHostedAgentInvokeUrlPreview\(profile\)/)
  assert.match(section, /t\('ai\.connection\.resolvedTokenUrl'\)/)
  assert.match(section, /t\('ai\.connection\.resolvedInvokeUrl'\)/)
  assert.match(runtime, /AI_PROVIDER_STATE_CHANGED_EVENT/)
  assert.match(runtime, /document\.addEventListener\(AI_PROVIDER_STATE_CHANGED_EVENT, handleProviderStateChanged\)/)
  assert.match(runtime, /document\.removeEventListener\(AI_PROVIDER_STATE_CHANGED_EVENT, handleProviderStateChanged\)/)
})
