import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('wysiwyg task list live preview wires custom bullets, checkbox widgets, and editable active-line fallbacks', async () => {
  const source = await readFile(new URL('../src/components/Editor/wysiwyg.ts', import.meta.url), 'utf8')

  assert.match(source, /class CheckboxWidget extends WidgetType/u)
  assert.ok(source.includes("el.className = `cm-wysiwyg-checkbox ${this.checked ? 'is-checked' : ''}`"))
  assert.ok(source.includes("el.setAttribute('role', 'checkbox')"))
  assert.ok(source.includes("el.setAttribute('aria-checked', String(this.checked))"))
  assert.ok(source.includes("el.setAttribute('aria-keyshortcuts', 'Enter Space')"))
  assert.ok(source.includes('el.tabIndex = 0'))
  assert.match(source, /class ListBulletWidget extends WidgetType/u)
  assert.match(source, /class OrderedListMarkerWidget extends WidgetType/u)
  assert.match(source, /function normalizeOrderedListMarker\(marker: string\): string \{/u)
  assert.match(source, /function resolveUnorderedListMarkerKind\(depth: number\): 'disc' \| 'circle' \| 'square' \{/u)
  assert.ok(source.includes("if (depth <= 0) return 'disc'"))
  assert.ok(source.includes("if (depth === 1) return 'circle'"))
  assert.ok(source.includes("return 'square'"))
  assert.ok(source.includes("el.className = `cm-wysiwyg-bullet-simple cm-wysiwyg-bullet-simple--${resolveUnorderedListMarkerKind(this.depth)}`"))
  assert.ok(source.includes("el.className = 'cm-wysiwyg-ordered-number'"))
  assert.ok(source.includes("el.setAttribute('aria-hidden', 'true')"))

  assert.ok(source.includes("const listMatch = text.match(/^(\\s*)([-*+]|\\d+[.)])(\\s+)/)"))
  assert.ok(source.includes("const taskMatch = text.match(/^(\\s*)([-*+]\\s+\\[(?: |x|X)\\])(\\s*)/)"))
  assert.ok(source.includes("Decoration.replace({ widget: new OrderedListMarkerWidget(marker) })"))
  assert.ok(source.includes("Decoration.replace({ widget: new ListBulletWidget(depth) })"))
  assert.ok(source.includes("Decoration.replace({ widget: new CheckboxWidget(isChecked, mStart, label) })"))
  assert.ok(source.includes("Decoration.mark({ class: 'cm-wysiwyg-task-marker' })"))
  assert.ok(source.includes("Decoration.mark({ class: 'cm-wysiwyg-task-completed' })"))
  assert.ok(source.includes("checkbox.classList.toggle('is-checked')"))
  assert.match(
    source,
    /closest\('\.cm-wysiwyg-checkbox'\)[\s\S]*?event\.preventDefault\(\)[\s\S]*?return true/u,
  )
  assert.match(source, /'\.cm-wysiwyg-checkbox:focus-visible': \{[\s\S]*?outline:[\s\S]*?boxShadow:/u)

  assert.ok(source.includes("'.cm-wysiwyg-task-completed': {"))
  assert.ok(source.includes("'.cm-wysiwyg-task-marker': {"))
  assert.ok(source.includes("'.cm-wysiwyg-bullet-simple': {"))
  assert.ok(source.includes("'.cm-wysiwyg-ordered-number': {"))
  assert.ok(source.includes("'.cm-wysiwyg-checkbox.is-checked .checkmark': {"))
  const taskCompletedStyleMatch = source.match(/'\.cm-wysiwyg-task-completed': \{([\s\S]*?)\n  \},/u)
  assert.ok(taskCompletedStyleMatch)
  const taskCompletedStyle = taskCompletedStyleMatch[1]
  assert.match(taskCompletedStyle, /color: 'var\(--md-task-completed-color, color-mix\(in srgb, var\(--preview-text\) 68%, var\(--text-muted\)\)\) !important'/u)
  assert.match(taskCompletedStyle, /transition: 'color 0\.2s ease'/u)
  assert.doesNotMatch(taskCompletedStyle, /textDecoration/u)
  assert.match(source, /const LIST_MARKER_INLINE_SIZE = 'var\(--md-list-marker-inline-size, 1ch\)'/u)
  assert.match(source, /const LIST_MARKER_FONT_WEIGHT = 'var\(--md-list-marker-font-weight, 400\)'/u)
  assert.match(source, /const LIST_MARKER_DISC_SIZE = 'var\(--md-list-bullet-disc-size, 0\.33em\)'/u)
  assert.match(source, /const LIST_MARKER_CIRCLE_SIZE = 'var\(--md-list-bullet-circle-size, 0\.33em\)'/u)
  assert.match(source, /const LIST_MARKER_SQUARE_SIZE = 'var\(--md-list-bullet-square-size, 0\.27em\)'/u)
  assert.match(source, /const LIST_MARKER_CIRCLE_STROKE = 'var\(--md-list-bullet-circle-stroke, 1px\)'/u)
  assert.match(source, /const LIST_MARKER_GAP = 'var\(--md-list-marker-gap, 0\.9em\)'/u)
  assert.match(source, /const LIST_ORDERED_MARKER_GAP = 'var\(--md-list-ordered-marker-gap, 0\.55em\)'/u)
  assert.match(source, /const LIST_MARKER_OFFSET_Y = 'var\(--md-list-marker-offset-y, 0em\)'/u)
  assert.match(source, /type WysiwygListMarkerKind = 'ordered' \| 'unordered'/u)
  assert.match(source, /const markerGap = markerKind === 'ordered' \? LIST_ORDERED_MARKER_GAP : LIST_MARKER_GAP/u)
  assert.match(source, /function buildWysiwygListLineStyle\(depth: number, markerKind: WysiwygListMarkerKind\): string \{/u)
  assert.match(source, /class: 'cm-wysiwyg-list-line cm-wysiwyg-list-line--ordered'[\s\S]*?style: buildWysiwygListLineStyle\(depth, 'ordered'\)/u)
  assert.match(source, /class: 'cm-wysiwyg-list-line cm-wysiwyg-list-line--unordered'[\s\S]*?style: buildWysiwygListLineStyle\(depth, 'unordered'\)/u)
  assert.match(source, /lineFrom,\s*prefixEnd,\s*Decoration\.replace\(\{ widget: new OrderedListMarkerWidget\(marker\) \}\)/u)
  assert.match(source, /lineFrom,\s*prefixEnd,\s*Decoration\.replace\(\{ widget: new ListBulletWidget\(depth\) \}\)/u)
  assert.match(source, /function parseWysiwygListLine\(text: string\): \{ depth: number; ordered: boolean \} \| null \{/u)
  assert.match(source, /function isWysiwygLooseListSpacerLine\(doc: CodeMirrorState\['doc'\], lineNumber: number\): boolean \{/u)
  assert.match(source, /Decoration\.line\(\{ attributes: \{ class: 'cm-wysiwyg-list-spacer-line' \} \}\)/u)
  assert.match(source, /isWysiwygLooseListSpacerLine\(doc, lineNumber\)[\s\S]*?markers\.set\(line\.from, hiddenGutterMarker\)/u)
  assert.match(source, /'\.cm-wysiwyg-list-spacer-line': \{[\s\S]*?height: '0'[\s\S]*?padding: '0 !important'[\s\S]*?overflow: 'hidden'/u)
  assert.match(source, /'\.cm-wysiwyg-list-line': \{[\s\S]*?position: 'relative'[\s\S]*?paddingLeft: 'var\(--cm-wysiwyg-list-text-inset\) !important'/u)
  assert.match(source, /'\.cm-wysiwyg-bullet-simple': \{[\s\S]*?display: 'inline-block'[\s\S]*?position: 'absolute'[\s\S]*?insetInlineStart: 'var\(--cm-wysiwyg-list-marker-inset\)'[\s\S]*?transform: 'translateX\(-50%\)'[\s\S]*?width: LIST_MARKER_INLINE_SIZE[\s\S]*?height: 'calc\(1em \* var\(--md-prose-line-height, 1\.8\)\)'[\s\S]*?color: 'var\(--md-list-marker-color, var\(--preview-text\)\) !important'[\s\S]*?fontWeight: LIST_MARKER_FONT_WEIGHT[\s\S]*?lineHeight: PROSE_LINE_HEIGHT[\s\S]*?verticalAlign: 'top'[\s\S]*?pointerEvents: 'none'/u)
  assert.match(source, /'\.cm-wysiwyg-bullet-simple::before': \{[\s\S]*?content: '""'[\s\S]*?position: 'absolute'[\s\S]*?top: '50%'[\s\S]*?left: '50%'[\s\S]*?transform: `translate\(-50%, calc\(-50% \+ \$\{LIST_MARKER_OFFSET_Y\}\)\)`/u)
  assert.match(source, /'\.cm-wysiwyg-bullet-simple--disc::before': \{[\s\S]*?width: LIST_MARKER_DISC_SIZE[\s\S]*?borderRadius: '999px'[\s\S]*?backgroundColor: 'currentColor'/u)
  assert.match(source, /'\.cm-wysiwyg-bullet-simple--circle::before': \{[\s\S]*?width: LIST_MARKER_CIRCLE_SIZE[\s\S]*?border: `\$\{LIST_MARKER_CIRCLE_STROKE\} solid currentColor`[\s\S]*?backgroundColor: 'transparent'/u)
  assert.match(source, /'\.cm-wysiwyg-bullet-simple--square::before': \{[\s\S]*?width: LIST_MARKER_SQUARE_SIZE[\s\S]*?backgroundColor: 'currentColor'/u)
  assert.match(source, /'\.cm-wysiwyg-ordered-number': \{[\s\S]*?display: 'inline-block'[\s\S]*?position: 'absolute'[\s\S]*?insetInlineStart: 'var\(--cm-wysiwyg-list-marker-inset\)'[\s\S]*?transform: 'translateX\(-100%\)'[\s\S]*?fontFamily: PREVIEW_FONT_FAMILY[\s\S]*?color: 'var\(--md-list-marker-color, var\(--preview-text\)\) !important'[\s\S]*?fontWeight: LIST_MARKER_FONT_WEIGHT[\s\S]*?textAlign: 'right'[\s\S]*?whiteSpace: 'nowrap'[\s\S]*?pointerEvents: 'none'/u)
  assert.match(source, /'\.cm-wysiwyg-checkbox': \{[\s\S]*?width: 'var\(--md-task-checkbox-size, 16px\)'[\s\S]*?height: 'var\(--md-task-checkbox-size, 16px\)'[\s\S]*?marginRight: 'var\(--md-task-checkbox-gap, 8px\)'[\s\S]*?borderRadius: 'var\(--md-task-checkbox-radius, 4px\)'/u)
})

test('preview task list styles target semantic GFM task list markup and custom checkbox chrome', async () => {
  const css = await readFile(new URL('../src/global.css', import.meta.url), 'utf8')

  assert.match(css, /\.markdown-preview ul\s*\{[\s\S]*list-style-type:\s*disc;/u)
  assert.match(css, /\.markdown-preview ul ul\s*\{[\s\S]*list-style-type:\s*circle;/u)
  assert.match(css, /\.markdown-preview ul ul ul\s*\{[\s\S]*list-style-type:\s*square;/u)
  assert.match(css, /\.markdown-preview ul\.contains-task-list,\s*\.markdown-preview ul\.contains-task-list ul\.contains-task-list\s*\{/u)
  assert.match(css, /\.markdown-preview li\.task-list-item\s*\{/u)
  assert.match(css, /\.markdown-preview li\.task-list-item > input\[type="checkbox"\]\s*\{/u)
  assert.match(css, /\.markdown-preview li::marker\s*\{[\s\S]*color:\s*var\(--md-list-marker-color, var\(--preview-text\)\);[\s\S]*font-weight:\s*var\(--md-list-marker-font-weight, 400\);/u)
  const checkedTaskStyleMatch = css.match(/\.markdown-preview li\.task-list-item:has\(> input\[type="checkbox"\]:checked\)\s*\{([\s\S]*?)\n\}/u)
  assert.ok(checkedTaskStyleMatch)
  const checkedTaskStyle = checkedTaskStyleMatch[1]
  assert.match(checkedTaskStyle, /color:\s*var\(--md-task-completed-color/u)
  assert.match(checkedTaskStyle, /transition:\s*color 0\.2s ease;/u)
  assert.doesNotMatch(checkedTaskStyle, /text-decoration/u)
  assert.match(css, /\.markdown-preview input\[type="checkbox"\]\s*\{[\s\S]*appearance:\s*none;/u)
  assert.match(css, /\.markdown-preview input\[type="checkbox"\]\s*\{[\s\S]*width:\s*var\(--md-task-checkbox-size, 16px\);[\s\S]*margin-right:\s*var\(--md-task-checkbox-gap, 8px\);[\s\S]*border-radius:\s*var\(--md-task-checkbox-radius, 4px\);/u)
  assert.match(css, /\.markdown-preview input\[type="checkbox"\]:checked\s*\{/u)
  assert.match(css, /\.markdown-preview input\[type="checkbox"\]::after\s*\{/u)
  assert.match(css, /\.markdown-preview input\[type="checkbox"\]:checked::after\s*\{/u)
})
