export interface AppTheme {
  id: string
  name: string
  dark: boolean
  vars: Record<string, string>
}

export const THEMES: AppTheme[] = [
  {
    id: 'default-light',
    name: 'Default Light',
    dark: false,
    vars: {
      '--bg-primary': '#FAFAFA',
      '--bg-secondary': '#F4F4F5',
      '--bg-tertiary': '#E4E4E7',
      '--bg-sidebar': '#F0F0F2',
      '--border': '#D4D4D8',
      '--text-primary': '#18181B',
      '--text-secondary': '#52525B',
      '--text-muted': '#A1A1AA',
      '--accent': '#3B82F6',
      '--accent-hover': '#2563EB',
      '--toolbar-bg': '#FFFFFF',
      '--statusbar-bg': '#3B82F6',
      '--statusbar-text': '#FFFFFF',
      '--editor-bg': '#FFFFFF',
      '--editor-text': '#1A1A1A',
      '--editor-line-active': 'rgba(59,130,246,0.05)',
      '--editor-selection': 'rgba(59,130,246,0.2)',
      '--editor-cursor': '#3B82F6',
      '--preview-bg': '#FAFAFA',
      '--preview-text': '#1A1A1A',
    },
  },
  {
    id: 'default-dark',
    name: 'Default Dark',
    dark: true,
    vars: {
      '--bg-primary': '#1E1E2E',
      '--bg-secondary': '#181825',
      '--bg-tertiary': '#11111B',
      '--bg-sidebar': '#181825',
      '--border': '#313244',
      '--text-primary': '#CDD6F4',
      '--text-secondary': '#BAC2DE',
      '--text-muted': '#6C7086',
      '--accent': '#89B4FA',
      '--accent-hover': '#B4BEFE',
      '--toolbar-bg': '#181825',
      '--statusbar-bg': '#89B4FA',
      '--statusbar-text': '#1E1E2E',
      '--editor-bg': '#1E1E2E',
      '--editor-text': '#CDD6F4',
      '--editor-line-active': 'rgba(137,180,250,0.05)',
      '--editor-selection': 'rgba(137,180,250,0.2)',
      '--editor-cursor': '#89B4FA',
      '--preview-bg': '#1E1E2E',
      '--preview-text': '#CDD6F4',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    dark: false,
    vars: {
      '--bg-primary': '#FFFFFF',
      '--bg-secondary': '#F6F8FA',
      '--bg-tertiary': '#EAEEF2',
      '--bg-sidebar': '#F6F8FA',
      '--border': '#D0D7DE',
      '--text-primary': '#1F2328',
      '--text-secondary': '#656D76',
      '--text-muted': '#9198A1',
      '--accent': '#0969DA',
      '--accent-hover': '#0550AE',
      '--toolbar-bg': '#F6F8FA',
      '--statusbar-bg': '#0969DA',
      '--statusbar-text': '#FFFFFF',
      '--editor-bg': '#FFFFFF',
      '--editor-text': '#1F2328',
      '--editor-line-active': 'rgba(9,105,218,0.04)',
      '--editor-selection': 'rgba(9,105,218,0.15)',
      '--editor-cursor': '#0969DA',
      '--preview-bg': '#FFFFFF',
      '--preview-text': '#1F2328',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    dark: true,
    vars: {
      '--bg-primary': '#0D1117',
      '--bg-secondary': '#161B22',
      '--bg-tertiary': '#21262D',
      '--bg-sidebar': '#161B22',
      '--border': '#30363D',
      '--text-primary': '#E6EDF3',
      '--text-secondary': '#8D96A0',
      '--text-muted': '#6E7681',
      '--accent': '#58A6FF',
      '--accent-hover': '#79C0FF',
      '--toolbar-bg': '#161B22',
      '--statusbar-bg': '#238636',
      '--statusbar-text': '#FFFFFF',
      '--editor-bg': '#0D1117',
      '--editor-text': '#E6EDF3',
      '--editor-line-active': 'rgba(88,166,255,0.05)',
      '--editor-selection': 'rgba(88,166,255,0.2)',
      '--editor-cursor': '#58A6FF',
      '--preview-bg': '#0D1117',
      '--preview-text': '#E6EDF3',
    },
  },
  {
    id: 'notion-light',
    name: 'Notion',
    dark: false,
    vars: {
      '--bg-primary': '#FFFFFF',
      '--bg-secondary': '#F7F7F5',
      '--bg-tertiary': '#EEEEEC',
      '--bg-sidebar': '#F7F7F5',
      '--border': '#E9E9E7',
      '--text-primary': '#37352F',
      '--text-secondary': '#787774',
      '--text-muted': '#ACABA8',
      '--accent': '#2383E2',
      '--accent-hover': '#0F73D9',
      '--toolbar-bg': '#FFFFFF',
      '--statusbar-bg': '#37352F',
      '--statusbar-text': '#FFFFFF',
      '--editor-bg': '#FFFFFF',
      '--editor-text': '#37352F',
      '--editor-line-active': 'rgba(35,131,226,0.04)',
      '--editor-selection': 'rgba(35,131,226,0.15)',
      '--editor-cursor': '#2383E2',
      '--preview-bg': '#FFFFFF',
      '--preview-text': '#37352F',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    dark: true,
    vars: {
      '--bg-primary': '#2E3440',
      '--bg-secondary': '#3B4252',
      '--bg-tertiary': '#434C5E',
      '--bg-sidebar': '#3B4252',
      '--border': '#4C566A',
      '--text-primary': '#ECEFF4',
      '--text-secondary': '#D8DEE9',
      '--text-muted': '#4C566A',
      '--accent': '#88C0D0',
      '--accent-hover': '#81A1C1',
      '--toolbar-bg': '#3B4252',
      '--statusbar-bg': '#5E81AC',
      '--statusbar-text': '#ECEFF4',
      '--editor-bg': '#2E3440',
      '--editor-text': '#ECEFF4',
      '--editor-line-active': 'rgba(136,192,208,0.05)',
      '--editor-selection': 'rgba(136,192,208,0.2)',
      '--editor-cursor': '#88C0D0',
      '--preview-bg': '#2E3440',
      '--preview-text': '#ECEFF4',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    dark: false,
    vars: {
      '--bg-primary': '#FDF6E3',
      '--bg-secondary': '#EEE8D5',
      '--bg-tertiary': '#DDD6C1',
      '--bg-sidebar': '#EEE8D5',
      '--border': '#D3CBAC',
      '--text-primary': '#657B83',
      '--text-secondary': '#839496',
      '--text-muted': '#93A1A1',
      '--accent': '#268BD2',
      '--accent-hover': '#1E6FA8',
      '--toolbar-bg': '#FDF6E3',
      '--statusbar-bg': '#268BD2',
      '--statusbar-text': '#FDF6E3',
      '--editor-bg': '#FDF6E3',
      '--editor-text': '#657B83',
      '--editor-line-active': 'rgba(38,139,210,0.05)',
      '--editor-selection': 'rgba(38,139,210,0.15)',
      '--editor-cursor': '#268BD2',
      '--preview-bg': '#FDF6E3',
      '--preview-text': '#657B83',
    },
  },
  {
    id: 'ia-writer',
    name: 'iA Writer',
    dark: false,
    vars: {
      '--bg-primary': '#FFFFFF',
      '--bg-secondary': '#F5F5F5',
      '--bg-tertiary': '#EBEBEB',
      '--bg-sidebar': '#F5F5F5',
      '--border': '#E0E0E0',
      '--text-primary': '#1A1A1A',
      '--text-secondary': '#6B6B6B',
      '--text-muted': '#ABABAB',
      '--accent': '#40A0FF',
      '--accent-hover': '#2080E0',
      '--toolbar-bg': '#FFFFFF',
      '--statusbar-bg': '#1A1A1A',
      '--statusbar-text': '#FFFFFF',
      '--editor-bg': '#FFFFFF',
      '--editor-text': '#1A1A1A',
      '--editor-line-active': 'rgba(64,160,255,0.04)',
      '--editor-selection': 'rgba(64,160,255,0.18)',
      '--editor-cursor': '#40A0FF',
      '--preview-bg': '#FFFFFF',
      '--preview-text': '#1A1A1A',
    },
  },
]

export function applyTheme(theme: AppTheme): void {
  const root = document.documentElement
  // Set dark class
  root.classList.toggle('dark', theme.dark)
  // Apply CSS vars
  for (const [key, val] of Object.entries(theme.vars)) {
    root.style.setProperty(key, val)
  }
}

export function getThemeById(id: string): AppTheme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0]
}
